export const data = {
  NavDashboard: {
    inbox: 4,
    drive_files: 435,
    boards: 5,
    updates: 0,
    analytics: 2,
    crm_dashboard: 2,
    ecommerce: 0,
    cryptocurrency: 0,
    projects: 0,
    nft_marketplace: 0,
    settings: 2,
  },

  Projects: {
    additional_calendar: 6,
    branch_logo_design: 11,
    user_research: 0,
    marketing_sales: 23,
    new_project_template: 2,
  },

  Users: {
    user1: {
      id: 1,
      message: 5,
      status: "offline",
      isUser: false,
    },
    user2: {
      id: 2,
      message: 0,
      status: "offline",
      isUser: false,
    },
    user3: {
      id: 3,
      message: 0,
      status: "offline",
      isUser: false,
    },
    user4: {
      id: 4,
      message: 9,
      status: "offline",
      isUser: false,
    },
    user5: {
      id: 5,
      message: 1,
      status: "offline",
      isUser: false,
    },
    user6: {
      id: 0,
      message: 0,
      status: "online",
      isUser: true,
    },
    user7: {
      id: 1,
      message: 0,
      status: "offline",
      isUser: false,
    },
    user8: {
      id: 2,
      message: 0,
      status: "offline",
      isUser: false,
    },
    user9: {
      id: 3,
      message: 7,
      status: "offline",
      isUser: false,
    },
    user10: {
      id: 4,
      message: 9,
      status: "offline",
      isUser: false,
    },
    user11: {
      id: 1,
      message: 4,
      status: "offline",
      isUser: false,
    },
    user12: {
      id: 2,
      message: 0,
      status: "offline",
      isUser: false,
    },
    user13: {
      id: 3,
      message: 0,
      status: "offline",
      isUser: false,
    },
    user14: {
      id: 4,
      message: 6,
      status: "offline",
      isUser: false,
    },
    user15: {
      id: 5,
      message: 3,
      status: "offline",
      isUser: false,
    },
  },

  Timeline: {
    Backlog: {
      total: 5,
      content: [
        {
          category:"Backlog",
          title: "Modal Answer",
          total: 4,
          id: "#UI007",
          tag: "Design",
          files: 4,
          comment: 4,
        },
        {
          category:"Backlog",
          title: "Create calendar, chat and email app pages",
          total: 1,
          id: "#UI003",
          tag: "Development",
          files: 2,
          comment: 2,
        },
        {
          category:"Backlog",
          title: "Product Design, Figma, Sketch (Software), Prototype",
          total: 4,
          id: "#BC05",
          tag: "Project",
          files: 2,
          comment: 4,
        },
        {
          category:"Backlog",
          title: "Change email option process",
          total: 4,
          id: "#FTC07",
          files: 2,
          comment: 2,
        },
        {
          category:"Backlog",
          title: "Post launch reminder/ Post list",
          total: 0,
          id: "#UI006",
          tag: "Design",
          files: 0,
          comment: 0,
        },
      ],
    },
    Todo: {
      total: 4,
      content: [
        {
          category:"To Do",
          title: "Modal Answer",
          total: 4,
          id: "#UI002",
          tag: "Design",
          files: 4,
          comment: 4,
        },
        {
          category:"To Do",
          title: "Add authentication pages",
          total: 0,
          id: "#FTC55",
          files: 0,
          comment: 0,
        },
        {
          category:"To Do",
          title: "Profile Page Satructure",
          total: 0,
          id: "#FTC09",
          files: 0,
          comment: 0,
        },
        {
          category:"To Do",
          title: "Create calendar, chat and email app pages",
          total: 2,
          id: "#FTC37",
          files: 1,
          comment: 1,
        }
      ],
    },
    InProgress: {
      total: 2,
      content: [
        {
          category:"In Progress",
          title: "Modal Answer",
          total: 4,
          id: "#UX022",
          tag: "Design",
          files: 4,
          comment: 4,
        },
        {
          category:"In Progress",
          title: "Create calendar, chat and email app pages",
          total: 2,
          id: "#FXC55",
          files: 1,
          comment: 1,
        },
      ],
    },
    Done: {
      total: 5,
      content: [
        {
          category:"Done",
          title: "Modal Answer",
          id: "#UI007",
          files: 0,
          comment: 0,
        },
        {
          category:"Done",
          title: "Create calendar, chat and email app pages",
          id: "#UI003",
          files: 0,
          comment: 0,
        },
        {
          category:"Done",
          title: "Product Design, Figma, Sketch (Software), Prototype",
          id: "#BC05",
          files: 0,
          comment: 0,
        },
        {
          category:"Done",
          title: "Model Answer",
          id: "#FTC07",
          files: 0,
          comment: 0,
        },
        {
          category:"Done",
          title: "Create calendar, chat and email app pages",
          id: "#FTCR5",
          files: 0,
          comment: 0,
        },
      ],
    },
  },
};
